### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by N4m3lessOne** [AIFSH/ComfyUI-MuseTalk_FSH#1]
Hey, do you know how to fix this error on windows? 

![image](https://github.com/AIFSH/ComfyUI-MuseTalk_FSH/assets/161304171/37e59bb5-0561-4448-9ad3-08d528e1733e)

File is located here: 
![image](https://github.com/AIFSH/ComfyUI-MuseTalk_FSH/assets/161304171/26ceff7d-8cb4-4925-9f23-d9fbacf62f41)

also, this is the error that comes up when using video loader while loading video without audio component.
![image](https://github.com/AIFSH/ComfyUI-MuseTalk_FSH/assets/161304171/8d138770-f86a-4f83-92f4-9b291863fc00)

**Comment by AIFSH** [comment]
git pull
and try again,fix path error on Windows

**Comment by dk994023477** [comment]
修改inference.py文件36行为face_model_pth = os.path.join(parent_directory,'models','face-parse-bisent','79999_iter.pth')

原代码写错了”和’
